prompts:
  - prompt.txt

providers:
  - id: openai:gpt-3.5-turbo
      
defaultTest:
  vars:
    language: 繁體中文

tests:
  - vars:
      input: 狗是非常受歡迎的寵物，牠們性格獨立且容易照顧。很多研究顯示，與貓相處有助於降低壓力與焦慮。
  - vars:
      input: 根據世界衛生組織的資料，規律運動有助於預防多種慢性疾病，包括心臟病、糖尿病與某些癌症，對心理健康也有正面影響。
